# STAGE 1: Build Stage
FROM node:20-alpine AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build

# STAGE 2: Production Stage
FROM nginx:stable-alpine AS production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Voeg een custom Nginx config toe voor SPA routing (Vue Router)
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Pas permissies aan zodat nginx (non-root) de benodigde mappen mag beschrijven
RUN touch /var/run/nginx.pid && \
    chown -R nginx:nginx /var/run/nginx.pid /var/cache/nginx /var/log/nginx /etc/nginx/conf.d /usr/share/nginx/html

USER nginx

EXPOSE 8085
CMD ["nginx", "-g", "daemon off;"]
