FROM vroom-backend-base:latest

WORKDIR /app

# Create non-privileged user and group
RUN groupadd -g 10001 appgroup && \
    useradd -u 10000 -g appgroup -m -s /sbin/nologin appuser && \
    chown -R appuser:appgroup /app

COPY --chown=appuser:appgroup . .

USER appuser

# In productie gebruiken we gunicorn voor stabiliteit en meerdere workers (2 is genoeg voor lokale prod tests)
CMD ["gunicorn", "app.main:app", "-w", "2", "-k", "uvicorn.workers.UvicornWorker", "-b", "0.0.0.0:8000"]
