apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vroom-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/limit-connections: "20"
    nginx.ingress.kubernetes.io/limit-rps: "100"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  rules:
  - host: vroom.municipal.gov
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vroom-frontend-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: vroom-backend-service
            port:
              number: 8000
      - path: /map
        pathType: Prefix
        backend:
          service:
            name: vroom-sumo-web3d-service
            port:
              number: 5000
      - path: /socket.io
        pathType: Prefix
        backend:
          service:
            name: vroom-sumo-web3d-service
            port:
              number: 5678
